# Generated by Django 4.1.1 on 2022-10-01 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
