# Generated by Django 4.1.1 on 2022-10-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticket_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='completedDate',
            field=models.DateField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
