# Generated by Django 4.1.1 on 2022-10-01 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticket_completeddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='completedDate',
        ),
    ]
