# Generated by Django 4.1.1 on 2022-10-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_remove_ticket_completeddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='completedDate',
            field=models.DateField(blank=True, default='2022-12-31'),
            preserve_default=False,
        ),
    ]
