# Generated by Django 4.1.1 on 2022-10-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_alter_ticket_completeddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='completedBy',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
